version: '3.3'

services:
  postgres:
    image: postgres:15
    container_name: logging_postgres
    restart: always
    environment:
      POSTGRES_USER: nestjs
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: logs_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: logging_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redisdata:/data

  adminer:
    image: adminer
    container_name: logging_adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  pgdata:
  redisdata:
